# for one device, can be given like this:
hosts:
  - device: 10.209.16.204
    username: demo 
    passwd: demo123
tests:
  - /Users/awasthiy/Desktop/jsnap_temp/jsnapy/samples/test_not_in.yml 


###################################
#can send mail by specifying:
#mail: send_mail.yml

####################################
