# for one device, can be given like this:
hosts:
  - device: 10.209.16.204 
    username : demo 
    passwd: demo123
tests:
 - test_no_diff.yml 
 - test_delta.yml

# can use sqlite to store data and compare them  
#sqlite:
#  - store_in_sqlite: True
#    check_from_sqlite: True 
#    database_name: jbb.db
#    compare: 1,0

# can send mail by specifying mail
#mail: send_mail.yml
